### PR TITLE
remove bootstrapious readme

### PR DESCRIPTION
**Pull request by Rushi98**
Removed bootstrapious `readme` and linked their site in main `README.md`.

### CODE REVIEW

**Comment by SebastinSanty** [comment]
@Rushi98 I guess this was by mistake?

**Comment by Rushi98** [comment]
@SebastinSanty No. Having two readme's in a single folder can be confusing. So, I merged the two.

**Comment by SebastinSanty** [comment]
I can see only one README at present.

**Comment by Rushi98** [comment]
Yes, I deleted bootstrapious' readme. And provided a link to their site in the main README. So that there's only single readme and also one can go to the bootstrapious site should s/he needs further reference to the css and JavaScript files.

**Comment by 0xRampey** [comment]
Good. This seems to already be implemented. Closing request.

**Pull request closed without merging**
